# -----------------------------------------
# Configuration for `azurite` chart
# -----------------------------------------

nameOverride: null

fullnameOverride: null

image:
  name: mcr.microsoft.com/azure-storage/azurite
  pullPolicy: Always
  pullSecrets: []

config:
  blobs:
    enabled: true
    ## https://github.com/viters/azure-storage-init-containers
    initJob:
      enabled: false
      containers:
        public: ""
        private: ""
  queues:
    enabled: true
  tables:
    enabled: true
  skipApiVersionCheck: true

statefulset:
  affinity: {}
  annotations: {}
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsGroup: 10000
    runAsUser: 10000
    fsGroup: 10000
  replicaCount: 1
  resources: {}
  tolerations: []
  containerSecurityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false

service:
  type: ClusterIP
  labels: {}
  annotations: {}

persistentVolume:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: null

ingress:
  enabled: false
  labels: {}
  annotations: {}
  host:
    blobs: null
    queues: null
    tables: null
  className: "public"
  tls: []
